# Generated by Django 2.1.7 on 2019-02-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gettoken', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wx_access_token',
            old_name='once_time',
            new_name='created_time',
        ),
    ]
