# Generated by Django 2.1.7 on 2019-02-21 03:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0002_auto_20190221_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wx_access_token',
            name='once_time',
        ),
        migrations.AddField(
            model_name='wx_access_token',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
