# Generated by Django 2.1.7 on 2019-02-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wx', '0003_auto_20190221_0314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wx_Access_Token',
        ),
    ]
